import { format } from 'date-fns'

import { NOTICE_TYPE_LABELS, formatNoticeCurrency } from '@/lib/communication'
import type { OfficialNotice } from '@/types/communication'

interface NoticeDocumentProps {
  notice: OfficialNotice
  className?: string
}

export function NoticeDocument({ notice, className }: NoticeDocumentProps) {
  return (
    <div
      className={`mx-auto max-w-[210mm] bg-white p-8 text-sm text-gray-900 shadow-sm print:shadow-none ${className ?? ''}`}
      id="notice-document"
    >
      <div className="mb-6 border-b-2 border-regal-navy pb-4 text-center">
        <div className="mx-auto mb-3 flex size-16 items-center justify-center rounded-full bg-regal-navy/10">
          <div className="text-2xl font-bold text-regal-navy">🇮🇳</div>
        </div>
        <h1 className="text-lg font-bold uppercase tracking-wide text-regal-navy">
          Government of India
        </h1>
        <p className="text-xs text-gray-600">Ministry of Personnel, Public Grievances and Pensions</p>
        <p className="text-xs font-medium text-gray-700">{notice.department}</p>
        <p className="mt-2 text-[10px] uppercase tracking-widest text-gray-500">Official Notice</p>
      </div>

      <div className="mb-6 flex items-start justify-between gap-4 text-xs">
        <div>
          <p>
            <span className="font-semibold">Notice No:</span> {notice.id}
          </p>
          <p>
            <span className="font-semibold">Date:</span>{' '}
            {format(new Date(notice.generatedAt), 'dd MMMM yyyy')}
          </p>
        </div>
        <div className="text-right">
          <p>
            <span className="font-semibold">PPO No:</span> {notice.ppoNumber}
          </p>
          <p>
            <span className="font-semibold">Type:</span> {NOTICE_TYPE_LABELS[notice.noticeType]}
          </p>
        </div>
      </div>

      <div className="mb-6 rounded-lg border border-gray-200 bg-gray-50 p-4">
        <h2 className="mb-2 text-xs font-bold uppercase tracking-wide text-regal-navy">
          Pensioner Details
        </h2>
        <div className="grid gap-1 text-xs sm:grid-cols-2">
          <p>
            <span className="font-medium">Name:</span> {notice.pensionerName}
          </p>
          <p>
            <span className="font-medium">PPO Number:</span> {notice.ppoNumber}
          </p>
          {notice.amount != null && (
            <p>
              <span className="font-medium">Amount:</span> {formatNoticeCurrency(notice.amount)}
            </p>
          )}
          {notice.dueDate && (
            <p>
              <span className="font-medium">Due Date:</span>{' '}
              {format(new Date(notice.dueDate), 'dd MMMM yyyy')}
            </p>
          )}
        </div>
      </div>

      <div className="mb-8 whitespace-pre-wrap text-sm leading-relaxed text-gray-800">
        {notice.content}
      </div>

      {notice.supportingInfo && (
        <div className="mb-8 rounded-lg border border-dashed border-gray-300 p-3 text-xs text-gray-600">
          <p className="mb-1 font-semibold uppercase tracking-wide">Supporting Information</p>
          <p>{notice.supportingInfo}</p>
        </div>
      )}

      {notice.attachments.length > 0 && (
        <div className="mb-8 text-xs">
          <p className="mb-1 font-semibold">Attachments:</p>
          <ul className="list-inside list-disc text-gray-600">
            {notice.attachments.map((att) => (
              <li key={att.fileName}>{att.name}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="mt-12 border-t border-gray-200 pt-6">
        <div className="flex justify-between">
          <div className="text-xs text-gray-500">
            <p>Generated by: {notice.generatedBy}</p>
            <p>Generated on: {format(new Date(notice.generatedAt), 'dd MMM yyyy, hh:mm a')}</p>
          </div>
          <div className="text-center">
            <div className="mb-2 h-12 w-36 border-b border-gray-400" />
            <p className="text-xs font-medium">Authorized Signatory</p>
            <p className="text-[10px] text-gray-500">{notice.department}</p>
          </div>
        </div>
      </div>
    </div>
  )
}

export function printNoticeDocument() {
  const content = document.getElementById('notice-document')
  if (!content) return
  const printWindow = window.open('', '_blank')
  if (!printWindow) return
  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>Official Notice</title>
        <style>
          body { margin: 0; font-family: 'Georgia', serif; }
          @media print { body { margin: 0; } }
        </style>
      </head>
      <body>${content.outerHTML}</body>
    </html>
  `)
  printWindow.document.close()
  printWindow.focus()
  printWindow.print()
}
